### Local Env
@BASE_URL = http://localhost:8080
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzA4ZDcwNC02MDViLTQ2ZTctOWY4YS01YjVkZTYxOWM3NzciLCJpYXQiOjE3NDkyODU0NTF9.YXDrVLAVQg3KKzVu3e85bHgk9AV8sr3Yl75nEe53h3k

POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
    "email": "test@mail.com",
    "name": "test",
    "password": "Admin123"
}


### Login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "Admin123"
}

### Get User
GET {{BASE_URL}}/api/auth/me
Authorization: Bearer {{TOKEN}}